name: 'CI checks'

runs:
  using: 'composite'
  steps:
    - name: Build
      run: pnpm build
      shell: bash
    - name: Typecheck
      run: pnpm typecheck
      shell: bash
    - name: Install Playwright browsers
      run: pnpm dlx playwright install --with-deps
      shell: bash
    - name: Test React Flow
      run: pnpm test:react
      shell: bash
    # - name: Test Svelte Flow
    #   run: pnpm test:svelte
    #   shell: bash
